#!/bin/sh

. ./test/helper

test_exec_with_no_arguments() {
  touch "$APPLICATIONS/Xcode.app"
  touch "$APPLICATIONS/Xcode-9.3.app"
  touch "$APPLICATIONS/Xcode-9.4.app"

  xcodes=$(chxcode | tr '\n' ' ' | xargs)

  assertEquals "should print installed xcodes" "9.3 9.4" "$xcodes"
}

test_change_unknown_xcode_reports_error() {
  assertEquals "Unknown Xcode: 1.0" "$(chxcode 1.0 2>&1)"
}

test_change_unknown_xcode_exit_code() {
  chxcode 1.0 2 > /dev/null 2>&1
  assertEquals 1 $?
}

# shellcheck source=/dev/null
SHUNIT_PARENT=$0 . $SHUNIT2
