#!/bin/sh

. ./test/helper

test_exec_with_no_arguments() {
  touch "$APPLICATIONS/Xcode-9.3.app"
  touch "$APPLICATIONS/Xcode-9.4.app"

  xcodes=$(chxcode | tr '\n' ' ' | xargs)

  assertEquals "should print installed xcodes" "9.3 9.4" "$xcodes"
}

# shellcheck source=/dev/null
SHUNIT_PARENT=$0 . $SHUNIT2
