#!/bin/sh

log() {
	if [ -t 1 ]; then
		printf "\\x1b[1m\\x1b[32m>>>\\x1b[0m \\x1b[1m%s\\x1b[0m\\n" "$1"
	else
		printf ">>> %s\\n" "$1"
	fi
}

error=0

for test in ${0%/*}/*_test; do
	log "Running $test under $SHELL (interactive) ..."
  applications="$(mktemp -d)"
	APPLICATIONS="$applications" "$SHELL" "$@" -i "$test" || error=1
  rm -r "$applications"
	echo
done

for test in ${0%/*}/*_test; do
	log "Running $test under $SHELL (non-interactive) ..."
  applications="$(mktemp -d)"
	APPLICATIONS="$applications" "$SHELL" "$@" "$test" || error=1
  rm -r "$applications"
	echo
done

exit "$error"
