name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install shunit2
      run: brew install shunit2
    
    - name: Run tests
      run: make test
